#!/usr/bin/env bash
#this is a comment
counter=1

 

while [ $counter -le 10 ]

do

    if [ $counter -eq 9 ]

    then

        echo -e "Best School\nHi"

    else

        echo "Best School"

    fi

    ((counter++))

done


