#!/usr/bin/env bash
#this is a comment
for item in *

do

   

    if [[ $item == .* ]]

    then

        continue 

    fi

 

 

    name_part=$(echo "$item" | cut -d '-' -f 2-)

 

    echo "$name_part"

done
